#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F494A942E4616C2 (bruno@clisp.org)
#
Name     : libsigsegv
Version  : 2.12
Release  : 1
URL      : https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.12.tar.gz
Source0  : https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.12.tar.gz
Source99 : https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.12.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: libsigsegv-license = %{version}-%{release}

%description
GNU libsigsegv  -  Handling page faults in user mode
This is a library for handling page faults in user mode. A page fault
occurs when a program tries to access to a region of memory that is
currently not available. Catching and handling a page fault is a useful
technique for implementing:

%package dev
Summary: dev components for the libsigsegv package.
Group: Development
Provides: libsigsegv-devel = %{version}-%{release}

%description dev
dev components for the libsigsegv package.


%package license
Summary: license components for the libsigsegv package.
Group: Default

%description license
license components for the libsigsegv package.


%prep
%setup -q -n libsigsegv-2.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551208928
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1551208928
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libsigsegv
cp COPYING %{buildroot}/usr/share/package-licenses/libsigsegv/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsigsegv/COPYING
